=== ks-no/fiks-io-meldingstype-katalog/schema/no.ks.fiks.bekymringsmelding.privat.v1/no.ks.fiks.bekymringsmelding.privat.v1.schema.json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "$id": "https://fiks.ks.no/bekymringsmelding.privat.v1.schema.json",
  "title": "Privat bekymringsmelding",
  "type": "object",
  "definitions": {
    "adresse": {
      "type": "object",
      "required": [
        "adresselinje1"
      ],
      "properties": {
        "adresselinje1": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "adresselinje2": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "adresselinje3": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "postnummer": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "poststed": {
          "type": "string",
          "pattern": "^(.*)$"
        }
      }
    }
  },
  "required": [
    "kommunenummer",
    "kommunenavn",
    "bydelsnummer",
    "bydelsnavn",
    "melder",
    "barn",
    "melding"
  ],
  "properties": {
    "kommunenummer": {
      "type": "string",
      "pattern": "^\\d{4}$"
    },
    "kommunenavn": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "bydelsnummer": {
      "type": "string",
      "pattern": "^[0-9]{2}$"
    },
    "bydelsnavn": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "melder": {
      "type": "object",
      "required": [
        "fnr",
        "personnavn",
        "skjultIdentitet"
      ],
      "properties": {
        "fnr": {
          "type": "string",
          "pattern": "^[0-9]{11}$"
        },
        "personnavn": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "telefonnummer": {
          "type": "string",
          "pattern": "^[+]?[0-9]+([- ][0-9]+)*$"
        },
        "skjultIdentitet": {
          "type": "boolean"
        },
        "adresse": {
          "$ref": "#/definitions/adresse"
        }
      }
    },
    "barn": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "personnavn",
          "adresse"
        ],
        "properties": {
          "personnavn": {
            "type": "string",
            "pattern": "^(.*)$"
          },
          "antattAlder": {
            "type": "string",
            "pattern": "^(.*)$"
          },
          "relasjon": {
            "type": "string",
            "pattern": "^(.*)$"
          },
          "adresse": {
            "$ref": "#/definitions/adresse"
          }
        }
      }
    },
    "melding": {
      "type": "string",
      "pattern": "^(.*)$"
    }
  }
}

=== ks-no/fiks-io-meldingstype-katalog/schema/no.ks.fiks.bekymringsmelding.privat.v1/examples/privatBekymringsmelding.json
{
  "kommunenummer": "1201",
  "kommunenavn": "Bergen",
  "bydelsnummer": "02",
  "bydelsnavn": "Bergenhus",
  "melder": {
    "fnr": "22078347825",
    "personnavn": "Navnesen Navn Mellomnavn",
    "telefonnummer": "99999999",
    "skjultIdentitet": true,
    "adresse": {
      "adresselinje1": "Rosenkrantzgaten 3",
      "adresselinje2": "",
      "adresselinje3": "",
      "postnummer": "5003",
      "poststed": "Bergen"
    }
  },
  "barn": [
    {
      "personnavn": "Barn Barnesen",
      "antattAlder": "10",
      "relasjon": "Nabo, fritekstfelt",
      "adresse": {
        "adresselinje1": "RÃ¥dhusgaten 10",
        "adresselinje2": "",
        "adresselinje3": "",
        "postnummer": "5020",
        "poststed": "Bergen"
      }
    },
    {
      "personnavn": "Bare Barnet",
      "antattAlder": "10",
      "relasjon": "Nabo, fritekstfelt",
      "adresse": {
        "adresselinje1": "RÃ¥dhusgaten 10",
        "adresselinje2": "",
        "adresselinje3": "",
        "postnummer": "5020",
        "poststed": "Bergen"
      }
    }
  ],
  "melding": "Her kommer selve innholdet i bekymringsmeldingen!"
}
