=== ks-no/fiks-io-meldingstype-katalog/schema/no.ks.fiks.bekymringsmelding.offentlig.v1/no.ks.fiks.bekymringsmelding.offentlig.v1.schema.json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "$id": "https://fiks.ks.no/bekymringsmelding.offentlig.v1.schema.json",
  "type": "object",
  "definitions": {
    "adresse": {
      "type": "object",
      "required": [
        "adresselinje1"
      ],
      "properties": {
        "adresselinje1": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "adresselinje2": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "adresselinje3": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "postnummer": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "poststed": {
          "type": "string",
          "pattern": "^(.*)$"
        }
      }
    },
    "orientert": {
      "type": "boolean"
    },
    "orientertGrunn": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "personnavn": {
      "type": "string",
      "pattern": "^(.*)$"
    }
  },
  "required": [
    "kommunenummer",
    "kommunenavn",
    "bydelsnummer",
    "bydelsnavn",
    "melder",
    "barn",
    "foresatte",
    "melding"
  ],
  "properties": {
    "kommunenummer": {
      "type": "string",
      "pattern": "^\\d{4}$"
    },
    "kommunenavn": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "bydelsnummer": {
      "type": "string",
      "pattern": "^[0-9]{2}$"
    },
    "bydelsnavn": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "melder": {
      "type": "object",
      "required": [
        "fnr",
        "personnavn",
        "rolle",
        "telefonnummer",
        "epost",
        "virksomhet"
      ],
      "properties": {
        "fnr": {
          "type": "string",
          "pattern": "^[0-9]{11}$"
        },
        "personnavn": {
          "$ref": "#/definitions/personnavn"
        },
        "rolle": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "telefonnummer": {
          "type": "string",
          "pattern": "^[+]?[0-9]+([- ][0-9]+)*$"
        },
        "epost": {
          "type": "string",
          "pattern": "^[A-Za-zæøåÆØÅ0-9-_]+(\\.[A-Za-zæøåÆØÅ0-9-_]+)*@[A-Za-zæøåÆØÅ0-9-]+(\\.[A-Za-zæøåÆØÅ0-9-]+)*(\\.[A-Za-z]{2,})$"
        },
        "virksomhet": {
          "type": "object",
          "required": [
            "navn",
            "adresse"
          ],
          "properties": {
            "navn": {
              "type": "string",
              "pattern": "^(.*)$"
            },
            "orgnr": {
              "type": "string",
              "pattern": "^(.*)$"
            },
            "adresse": {
              "$ref": "#/definitions/adresse"
            }
          }
        }
      }
    },
    "barn": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "fnr",
          "ufoedt",
          "personnavn",
          "relasjon",
          "adresse",
          "orientert"
        ],
        "properties": {
          "fnr": {
            "type": "string",
            "pattern": "^(.*)$"
          },
          "ufoedt": {
            "type": "boolean"
          },
          "personnavn": {
            "$ref": "#/definitions/personnavn"
          },
          "telefonnummer": {
            "type": "string",
            "pattern": "^(.*)$"
          },
          "relasjon": {
            "type": "string",
            "pattern": "^(.*)$"
          },
          "adresse": {
            "$ref": "#/definitions/adresse"
          },
          "orientert": {
            "$ref": "#/definitions/orientert"
          },
          "orientertGrunn": {
            "$ref": "#/definitions/orientertGrunn"
          }
        }
      }
    },
    "foresatte": {
      "type": "array",
      "items": {
        "$id": "#/properties/foresatte/items",
        "type": "object",
        "required": [
          "personnavn",
          "orientert"
        ],
        "properties": {
          "personnavn": {
            "$ref": "#/definitions/personnavn"
          },
          "telefonnummer": {
            "type": "string",
            "pattern": "^(.*)$"
          },
          "orientert": {
            "$ref": "#/definitions/orientert"
          },
          "orientertGrunn": {
            "$ref": "#/definitions/orientertGrunn"
          }
        }
      }
    },
    "behovForTolk": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "andreHjelpeinstanser": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "melding": {
      "type": "object",
      "required": [
        "melding",
        "historie"
      ],
      "properties": {
        "melding": {
          "type": "string",
          "pattern": "^(.*)$"
        },
        "historie": {
          "type": "string",
          "pattern": "^(.*)$"
        }
      }
    }
  }
}

=== ks-no/fiks-io-meldingstype-katalog/schema/no.ks.fiks.bekymringsmelding.offentlig.v1/examples/offentligBekymringsmelding.json
{
  "kommunenummer": "1201",
  "kommunenavn": "Bergen",
  "bydelsnummer": "02",
  "bydelsnavn": "Bergenhus",
  "melder": {
    "fnr": "22078347825",
    "personnavn": "Navnesen Navn Mellomnavn",
    "rolle": "Lærer",
    "telefonnummer": "99999999",
    "epost": "lærer@skole.no",
    "virksomhet": {
      "navn": "Lærerskolen",
      "orgnr": "123455789",
      "adresse": {
        "adresselinje1": "Rosenkrantzgaten 3",
        "adresselinje2": "",
        "adresselinje3": "",
        "postnummer": "5003",
        "poststed": "Bergen"
      }
    }
  },
  "barn": [
    {
      "fnr": "28071364498",
      "ufoedt": false,
      "personnavn": "Barn Barnesen",
      "telefonnummer": "12121212",
      "relasjon": "Lærer",
      "adresse": {
        "adresselinje1": "Rådhusgaten 10",
        "adresselinje2": "",
        "adresselinje3": "",
        "postnummer": "5020",
        "poststed": "Bergen"
      },
      "orientert": false,
      "orientertGrunn": "Synes det er vanskelig å snakke om dette."
    },
    {
      "fnr": "16081688781",
      "ufoedt": false,
      "personnavn": "Bare Barnet",
      "telefonnummer": "13131313",
      "relasjon": "Lærer til søsteren",
      "adresse": {
        "adresselinje1": "Rådhusgaten 10",
        "adresselinje2": "",
        "adresselinje3": "",
        "postnummer": "5020",
        "poststed": "Bergen"
      },
      "orientert": false,
      "orientertGrunn": "Synes det er vanskelig å snakke om dette."
    }
  ],
  "foresatte": [
    {
      "personnavn": "Foresatt Foresatt",
      "telefonnummer": "45444342",
      "orientert": true,
      "orientertGrunn": ""
    }
  ],
  "behovForTolk": "Nei, de snakker norsk.",
  "andreHjelpeinstanser": "Nei, ikke vært i kontakt med andre hjelpeinstanser.",
  "melding": {
    "melding": "Her kommer selve innholdet i bekymringsmeldingen!",
    "historie": "Her kommer selve historien i bekymringsmeldingen!"
  }
}
